from flask import request
import timeline_app as timeline

app = timeline.app


@app.after_request
def ensure_contact_reviews_visible(response):
    """Make Contact & Reviews a reliable part of the current admin layout."""
    if request.path != '/admin' or not response.content_type or 'text/html' not in response.content_type:
        return response
    try:
        page = response.get_data(as_text=True)
        # timeline_app owns the forms/routes and builds the trusted admin section.
        if 'id="contact-reviews"' not in page:
            section = timeline.admin_contact_reviews_html()
            marker = '<section class="sec" id="security">'
            if marker in page:
                page = page.replace(marker, section + marker, 1)
            else:
                page = page.replace('</div>\n<script>', section + '</div>\n<script>', 1)

        # Current admin layout uses these exact navigation/shortcut markers.
        if 'href="#contact-reviews"' not in page:
            page = page.replace(
                '<a href="#branding">Branding</a><a href="#security">Security</a>',
                '<a href="#branding">Branding</a><a href="#contact-reviews">Contact & Reviews</a><a href="#security">Security</a>',
                1,
            )
        if 'class="q" href="#contact-reviews"' not in page:
            page = page.replace(
                '<a class="q" href="#branding">Branding</a><a class="q" href="#security">Security</a>',
                '<a class="q" href="#branding">Branding</a><a class="q" href="#contact-reviews">Contact & Reviews</a><a class="q" href="#security">Security</a>',
                1,
            )

        # Match the native admin card styling even though the section is generated by timeline_app.
        page = page.replace("class='section' id='contact-reviews'", "class='sec' id='contact-reviews'")
        page = page.replace("class='section-head'", "class='head'")
        page = page.replace("class='back-top'", "class='back'")
        page = page.replace("class='red'", "class='danger'")
        response.set_data(page)
        response.headers['Content-Length'] = str(len(response.get_data()))
    except Exception as exc:
        print('Contact dashboard enhancement failed:', exc)
    return response
